/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.handballscoutapp.GUI;

import com.mycompany.handballscoutapp.GolManager;
import javax.swing.JOptionPane;

/**
 *
 * @author ifmaker
 */
public class DlgGol extends javax.swing.JDialog {

    private GolManager golManager;

    public DlgGol(boolean modal, String time, String quadranteChute, String nomeArquivo) {
        setTitle("CHUTE: " + quadranteChute);
        golManager = new GolManager(time, quadranteChute, nomeArquivo);
        initComponents();
        bloquearBotao(false);

    }

    private void bloquearBotao(boolean flag) {
        this.jBtQuadranteGol1.setEnabled(flag);
        this.jBtQuadranteGol2.setEnabled(flag);
        this.jBtQuadranteGol3.setEnabled(flag);
        this.jBtQuadranteGol4.setEnabled(flag);
        this.jBtQuadranteGol5.setEnabled(flag);
        this.jBtQuadranteGol6.setEnabled(flag);
        this.jBtQuadranteGol7.setEnabled(flag);
        this.jBtQuadranteGol8.setEnabled(flag);
        this.jBtQuadranteGol9.setEnabled(flag);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jSlider1 = new javax.swing.JSlider();
        jPanel1 = new javax.swing.JPanel();
        jBtQuadranteGol1 = new javax.swing.JButton();
        jBtQuadranteGol2 = new javax.swing.JButton();
        jBtQuadranteGol3 = new javax.swing.JButton();
        jBtQuadranteGol4 = new javax.swing.JButton();
        jBtQuadranteGol5 = new javax.swing.JButton();
        jBtQuadranteGol6 = new javax.swing.JButton();
        jBtQuadranteGol7 = new javax.swing.JButton();
        jBtQuadranteGol8 = new javax.swing.JButton();
        jBtQuadranteGol9 = new javax.swing.JButton();
        jBtCancelarGol = new javax.swing.JButton();
        jBtTipoChuteDefesa = new javax.swing.JButton();
        jBtTipoChuteGol = new javax.swing.JButton();
        jBtTipoChuteFora = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        setResizable(false);

        jBtQuadranteGol1.setText("Q1 GOL");
        jBtQuadranteGol1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtQuadranteGol1ActionPerformed(evt);
            }
        });

        jBtQuadranteGol2.setText("Q2 GOL");
        jBtQuadranteGol2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtQuadranteGol2ActionPerformed(evt);
            }
        });

        jBtQuadranteGol3.setText("Q3 GOL");
        jBtQuadranteGol3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtQuadranteGol3ActionPerformed(evt);
            }
        });

        jBtQuadranteGol4.setText("Q4 GOL");
        jBtQuadranteGol4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtQuadranteGol4ActionPerformed(evt);
            }
        });

        jBtQuadranteGol5.setText("Q5 GOL");
        jBtQuadranteGol5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtQuadranteGol5ActionPerformed(evt);
            }
        });

        jBtQuadranteGol6.setText("Q6 GOL");
        jBtQuadranteGol6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtQuadranteGol6ActionPerformed(evt);
            }
        });

        jBtQuadranteGol7.setText("Q7 GOL");
        jBtQuadranteGol7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtQuadranteGol7ActionPerformed(evt);
            }
        });

        jBtQuadranteGol8.setText("Q8 GOL");
        jBtQuadranteGol8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtQuadranteGol8ActionPerformed(evt);
            }
        });

        jBtQuadranteGol9.setText("Q9 GOL");
        jBtQuadranteGol9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtQuadranteGol9ActionPerformed(evt);
            }
        });

        jBtCancelarGol.setText("CANCELAR GOL");
        jBtCancelarGol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtCancelarGolActionPerformed(evt);
            }
        });

        jBtTipoChuteDefesa.setText("DEFESA");
        jBtTipoChuteDefesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtTipoChuteDefesaMouseClicked(evt);
            }
        });
        jBtTipoChuteDefesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtTipoChuteDefesaActionPerformed(evt);
            }
        });

        jBtTipoChuteGol.setText("GOL");
        jBtTipoChuteGol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtTipoChuteGolMouseClicked(evt);
            }
        });
        jBtTipoChuteGol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtTipoChuteGolActionPerformed(evt);
            }
        });

        jBtTipoChuteFora.setText("FORA");
        jBtTipoChuteFora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtTipoChuteForaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBtTipoChuteDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtTipoChuteGol, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtTipoChuteFora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jSeparator2)
            .addComponent(jSeparator3)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtQuadranteGol1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtQuadranteGol2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtQuadranteGol3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtQuadranteGol4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtQuadranteGol5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtQuadranteGol6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtQuadranteGol7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtQuadranteGol8, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtQuadranteGol9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtCancelarGol, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(155, 155, 155))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtQuadranteGol2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtQuadranteGol3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtQuadranteGol1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtQuadranteGol4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtQuadranteGol6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtQuadranteGol5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtQuadranteGol7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtQuadranteGol8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtQuadranteGol9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jBtTipoChuteFora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtTipoChuteGol, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtTipoChuteDefesa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtCancelarGol, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtQuadranteGol1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtQuadranteGol1ActionPerformed
        golManager.verificarEExecutarAcao("Q1 GOL");
        setVisible(false);
    }//GEN-LAST:event_jBtQuadranteGol1ActionPerformed

    private void jBtQuadranteGol2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtQuadranteGol2ActionPerformed
        golManager.verificarEExecutarAcao("Q2 GOL");
        setVisible(false);
    }//GEN-LAST:event_jBtQuadranteGol2ActionPerformed

    private void jBtQuadranteGol3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtQuadranteGol3ActionPerformed
        golManager.verificarEExecutarAcao("Q3 GOL");
        setVisible(false);
    }//GEN-LAST:event_jBtQuadranteGol3ActionPerformed

    private void jBtQuadranteGol4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtQuadranteGol4ActionPerformed
        golManager.verificarEExecutarAcao("Q4 GOL");
        setVisible(false);
    }//GEN-LAST:event_jBtQuadranteGol4ActionPerformed

    private void jBtQuadranteGol5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtQuadranteGol5ActionPerformed
        golManager.verificarEExecutarAcao("Q5 GOL");
        setVisible(false);
    }//GEN-LAST:event_jBtQuadranteGol5ActionPerformed

    private void jBtQuadranteGol6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtQuadranteGol6ActionPerformed
        golManager.verificarEExecutarAcao("Q6 GOL");
        setVisible(false);
    }//GEN-LAST:event_jBtQuadranteGol6ActionPerformed

    private void jBtQuadranteGol7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtQuadranteGol7ActionPerformed
        golManager.verificarEExecutarAcao("Q7 GOL");
        setVisible(false);
    }//GEN-LAST:event_jBtQuadranteGol7ActionPerformed

    private void jBtQuadranteGol8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtQuadranteGol8ActionPerformed
        golManager.verificarEExecutarAcao("Q8 GOL");
        setVisible(false);
    }//GEN-LAST:event_jBtQuadranteGol8ActionPerformed

    private void jBtQuadranteGol9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtQuadranteGol9ActionPerformed
        golManager.verificarEExecutarAcao("Q9 GOL");
        setVisible(false);
    }//GEN-LAST:event_jBtQuadranteGol9ActionPerformed

    private void jBtTipoChuteDefesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtTipoChuteDefesaActionPerformed
        golManager.setTipoChute("DEFESA");
    }//GEN-LAST:event_jBtTipoChuteDefesaActionPerformed

    private void jBtTipoChuteGolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtTipoChuteGolActionPerformed
        golManager.setTipoChute("GOL");
    }//GEN-LAST:event_jBtTipoChuteGolActionPerformed

    private void jBtTipoChuteForaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtTipoChuteForaActionPerformed
        golManager.setTipoChute("FORA");
        int resposta = JOptionPane.showConfirmDialog(this, "CONFIRME SE O CHUTE FOI PARA FORA:", "CONFIRMAÇÃO DE CHUTE PARA FORA", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {
            golManager.salvarQuadranteChute(golManager.getQuadranteChuteFinal());

            this.setVisible(false);
        }
    }//GEN-LAST:event_jBtTipoChuteForaActionPerformed

    private void jBtCancelarGolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtCancelarGolActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this, "TEM CERTEZA QUE DESEJA CANCELAR ESTE CHUTE?", "CONFIRMAÇÃO DE CANCELAMENTO", JOptionPane.YES_NO_OPTION);

        if (resposta == JOptionPane.YES_OPTION) {
            // O usuário confirmou o cancelamento, volte para a tela inicial.
            this.setVisible(false);
        }
    }//GEN-LAST:event_jBtCancelarGolActionPerformed

    private void jBtTipoChuteGolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtTipoChuteGolMouseClicked
        bloquearBotao(true);
    }//GEN-LAST:event_jBtTipoChuteGolMouseClicked

    private void jBtTipoChuteDefesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtTipoChuteDefesaMouseClicked
        bloquearBotao(true);
    }//GEN-LAST:event_jBtTipoChuteDefesaMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtCancelarGol;
    private javax.swing.JButton jBtQuadranteGol1;
    private javax.swing.JButton jBtQuadranteGol2;
    private javax.swing.JButton jBtQuadranteGol3;
    private javax.swing.JButton jBtQuadranteGol4;
    private javax.swing.JButton jBtQuadranteGol5;
    private javax.swing.JButton jBtQuadranteGol6;
    private javax.swing.JButton jBtQuadranteGol7;
    private javax.swing.JButton jBtQuadranteGol8;
    private javax.swing.JButton jBtQuadranteGol9;
    private javax.swing.JButton jBtTipoChuteDefesa;
    private javax.swing.JButton jBtTipoChuteFora;
    private javax.swing.JButton jBtTipoChuteGol;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSlider jSlider1;
    // End of variables declaration//GEN-END:variables

}
